name: memoryrl
channels:
  - defaults
dependencies:
    - python=3.10.*
    - pip=21.0.*
    - pip:
        - numpy
        - pandas
        - matplotlib
        - notebook
        - vowpalwabbit==9.1.*
        - sklearn
        - coba==4.10.*