name: memoryrl
channels:
  - conda-forge
dependencies:
    - python=3.10.5
    - pip=21.2.*
    - pip:
        - numpy
        - pandas
        - matplotlib
        - notebook
        - vowpalwabbit==9.3.*
        - sklearn
        - coba==4.11.*